### ISSUE TITLE
Websocket parse error for market orders

### ISSUE THREAD

**Issue by rhinodavid** [escwdev/kucoin_rs#5]
`parse_message` in `websocket.rs` fails when parsing a market fill with error ``Serde(Error("missing field `price`", line: 1, column: 336))``. I placed the order from the web UI, but my guess is that this is an issue with match orders since there's no price associated with the order; only with the match.

Example JSON:

```
{
   "data":{
      "symbol":"VET-USDT",
      "orderType":"market",
      "side":"sell",
      "orderId":"5fdxxxxxxxxxxxxxxxxx",
      "liquidity":"taker",
      "type":"match",
      "orderTime":1608101947404986582,
      "size":"10",
      "filledSize":"10",
      "matchPrice":"0.0163897",
      "matchSize":"10",
      "tradeId":"5fdxxxxxxxxxxxxxxxxx",
      "remainSize":"0",
      "status":"match",
      "ts":1608101947404986582
   },
   "subject":"orderChange",
   "topic":"/spotMarket/tradeOrders",
   "channelType":"private",
   "type":"message",
   "userId":"xxxxxxxxxxxxxxxxx"
}
```

**Comment by rhinodavid** [comment]
I can spin up a fix this week or next. I think for now another default value for the field (as in #2) is fine, but maybe we could consider changing the model to use `Option` for some of these fields.

**Comment by escwdev** [comment]
Yeah, let's try with the default value for now since changing any existing fields to an `Option` can cause breaks for existing users. It could require some downstream changes to my bot at least.

Since I exclusively use limit orders I haven't tested all those endpoints, especially since the addition of the `/tradeOrders` endpoint. Since `price` is the main difference between the `market` and `limit` socket data, I think it makes sense to just make that field have `default` response for the type for all the related messages: `TradeOpen`, `TradeMatch`, `TradeFilled`, `TradeCanceled`, `TradeUpdate`.

That shouldn't cause any issues for existing end users and hopefully should cover the cases on any variation of the return socket data. Users will receive the same data for both `limit` and `market` orders and can differentiate based on the `orderType` or if `price` is `default` value.

If you don't get to this, I hopefully should be able to this week. I still also need to go over the formatting changes pull request as well. Once everything is integrated I'll do a cargo version change push too.

**Comment by escwdev** [comment]
I've added the serde default fields and did a quick test in the sandbox environment which was successful.

I'm going to close this issue for now but if further testing or user bugs reveal any issues, we can revisit it.
